services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/quotes
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
